# 빌드 스테이지
FROM node:latest AS frontend-build

WORKDIR /app

COPY package*.json ./

RUN yarn install

COPY . .

RUN yarn build

# 프로덕션 스테이지
FROM nginx:alpine as production-stage

COPY --from=frontend-build /app/dist /usr/share/nginx/html
COPY nginx-fe.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
