version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example_table
    volumes:
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d

  spring-boot-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql