version: '3'

networks:
  app-network:
    driver: bridge

services:
  mysql-container:
    networks:
      - app-network
    restart: unless-stopped
    image: mysql:latest
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example_db
    ports:
      - "3306:3306"
    volumes:
      - ./backend/script/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    networks:
      - app-network
    image: springboot-app:latest
    build:
      context: ./backend
      dockerfile: Dockerfile-prod-backend
    ports:
      - "9090:9090" # Remote 디버그 포트 포워딩
      - "8080:8080" # 웹 애플리케이션 포트 포워딩
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./backend:/workspace/app
    command:
      - bash
      - -c
      - |
        echo 'Waiting database container...'
        ./wait-for-it.sh mysql-container:3306 -s -t 0
        echo 'Starting backend container...'
        (./gradlew build -t &) && ./gradlew bootRun --args='--spring.profiles.active=dev'

  frontend:
    networks:
      - app-network
    image: react-vite-app:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod-frontend
    volumes:
      - ./frontend/src:/workspace/app/src
    ports:
      - "5200:5200"
    command: ["yarn", "dev", "--host", "--port", "5200"]

  # ... (다른 서비스와 설정은 현재 docker-compose.yaml 파일 참조)
