version: '3'
services:
  mysql-container:
    image: mysql:latest
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example_db
    ports:
      - "3306:3306"

  app:
    build: . # 현재 디렉토리에 있는 Dockerfile을 사용하여 빌드
    ports:
      - "8080:8080"
    depends_on:
      - mysql-container
    command:
      - bash
      - -c
      - |
        ./wait-for-it.sh mysql-container:3306 -s -t 0
        java -jar app.jar
