version: '3'

networks:
  app-network:
    driver: bridge

services:
  mysql-container:
    networks:
      - app-network
    restart: unless-stopped
    image: mysql:latest
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example_db
    ports:
      - "3306:3306"
    volumes:
      - ./backend/script/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    networks:
      - app-network
    image: springboot-app:latest
    build:
      context: ./backend
      dockerfile: Dockerfile-dev-backend
    ports:
      - "9090:9090" # Remote 디버그 포트 포워딩
      - "8080:8080" # 웹 애플리케이션 포트 포워딩
    environment:
      - SPRING_PROFILES_ACTIVE=dev
#      - JAVA_TOOL_OPTIONS=-Xmx512m -Xms256m -agentlib:jdwp=transport=dt_socket,address=*:9090,server=y,suspend=n
    #      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:9090,server=y,suspend=n
    volumes:
      - ./backend/src:/workspace/app/src
      - ./backend/build:/workspace/app/build
#      - ./backend:/workspace/app
    command:
      - bash
      - -c
      - |
        echo 'Waiting database container...'
        ./wait-for-it.sh mysql-container:3306 -s -t 0
        echo 'Starting backend container...'
        ./gradlew bootRun --args='--spring.profiles.active=dev'

  frontend:
    networks:
      - app-network
    image: react-vite-app:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev-frontend
    volumes:
      - ./frontend/src:/workspace/app/src
    ports:
      - "5173:5173"
    command: ["yarn", "dev", "--host"]

  # ... (다른 서비스와 설정은 현재 docker-compose.yaml 파일 참조)
