# 베이스 이미지 설정
FROM amazoncorretto:17

# 라벨링
LABEL authors="boki"

# 패키지 업데이트 및 supervisord 설치
#RUN yum -y update \
#    && yum install -y epel-release \
#    && yum install -y supervisor \
#    && mkdir -p /var/log/supervisor

#RUN yum -y update && yum install -y supervisor && mkdir -p /var/log/supervisor
RUN yum -y update && yum install -y supervisor

# 작업 디렉터리 설정
WORKDIR /workspace/app

# Supervisord 설정
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# 소스 코드 복사
COPY . .

# Gradle wrapper 실행 권한 설정
RUN chmod +x ./gradlew

# Spring Boot 빌드 (Kotlin)
RUN ./gradlew clean bootJar

# SQL 초기화 파일 복사
ADD ./script/init.sql /docker-entrypoint-initdb.d/

# 포트 노출
EXPOSE 3306 8080

# Supervisord 실행
CMD ["/usr/bin/supervisord"]

