spring:
  datasource:
    url: jdbc:mysql://localhost:3306/example_table?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    url: jdbc:mysql://127.0.0.1:3306/example_table?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
#    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver