spring:
  datasource:
    #useSSL=false&allowPublicKeyRetrieval=true
##    url: jdbc:mysql://localhost:3306/example_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    url: jdbc:mysql://127.0.0.1:3306/example_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    url: jdbc:mysql://mysql-container:3306/example_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create