# 알파인 리눅스: 경량화된 리눅스 배포판으로 컨테이너 용도로 인기가 많다
FROM alpine:latest

# 패키지 관리자: apk
# 무한히 실행 상태로 유지하게 하는 명령어: tail -f /dev/null

# 원하는 정보만 추출하여 출력
CMD echo "[OS Information]: $(cat /etc/os-release | grep 'PRETTY_NAME' | cut -d '=' -f 2) /" \
    "[Package Manager(apk)]: $(apk --version | head -n 1)" && \
    tail -f /dev/null