spring:
  devtools:
    restart:
      enabled: false
  datasource:
    url: jdbc:mysql://mysql-container:3306/example_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver