spring:
  devtools:
    restart:
      enabled: true
      additional-paths: .
#      additional-paths: ./src/main
#      exclude: static/**,public/**
    livereload:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/example_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
